CREATE DATABASE streamline;
USE streamline;

CREATE TABLE IF NOT EXISTS empresa (
  idEmpresa PRIMARY KEY INT AUTO_INCREMENT NOT NULL,
  nome VARCHAR(45) NOT NULL,
  cnpj VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  codigo CHAR(8) NOT NULL,
  senha VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS logradouro (
  idLogradouro PRIMARY KEY INT AUTO_INCREMENT NOT NULL,
  cep CHAR(8) NOT NULL,
  logradouro VARCHAR(100) NOT NULL,
  bairro VARCHAR(45) NOT NULL,
  cidade VARCHAR(45) NOT NULL,
  numero CHAR(8) NOT NULL,
  uf CHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS agencia (
  idAgencia PRIMARY KEY INT AUTO_INCREMENT NOT NULL,
  codigoAgencia VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  telefone VARCHAR(45) NOT NULL,
  fkEmpresa INT NOT NULL,
  fkLogradouro INT NOT NULL,
  FOREIGN KEY (fkEmpresa) REFERENCES empresa (idEmpresa),
  FOREIGN KEY (fkLogradouro) REFERENCES logradouro (idLogradouro)
);

CREATE TABLE IF NOT EXISTS usuario (
  idUsuario PRIMARY KEY INT AUTO_INCREMENT NOT NULL,
  nome VARCHAR(45) NOT NULL,
  telefone CHAR(11) NOT NULL,
  cargo VARCHAR(45) NOT NULL,
  email VARCHAR(45) UNIQUE NOT NULL,
  senha VARCHAR(45) NOT NULL,
  fkAgencia INT NOT NULL,
  FOREIGN KEY (fkAgencia) REFERENCES agencia (idAgencia)
);

CREATE TABLE IF NOT EXISTS atm (
  idAtm PRIMARY KEY INT AUTO_INCREMENT NOT NULL,
  nome VARCHAR(45) NOT NULL,
  modelo VARCHAR(45) NOT NULL,
  ip VARCHAR(45) NOT NULL,
  sistemaOperacional VARCHAR(45) NOT NULL,
  statusATM TINYINT NOT NULL,
  fkAgencia INT NOT NULL,
  FOREIGN KEY (fkAgencia) REFERENCES agencia (idAgencia)
);

CREATE TABLE IF NOT EXISTS componentes (
  idComponentes PRIMARY KEY INT AUTO_INCREMENT NOT NULL,
  componente VARCHAR(45) NULL,
  tipo VARCHAR(45) NOT NULL,
  limite DOUBLE NOT NULL,
  fkAtm INT NOT NULL,
  FOREIGN KEY (fkAtm) REFERENCES atm (idAtm)
);

CREATE TABLE IF NOT EXISTS captura1_1 (
  idCaptura INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CPUPercent DOUBLE NOT NULL,
  CPUFreq DOUBLE NOT NULL,
  RAMTotal DOUBLE NOT NULL,
  RAMDisponivel DOUBLE NULL,
  RAMPercentual DOUBLE NULL,
  DISKTotal DOUBLE NULL,
  DISKDisponivel DOUBLE NULL,
  DISKPercentual DOUBLE NULL,
  REDERecebida INT NULL, 
  REDEEnviada INT NULL, 
  PROCESSODesativado INT NULL, 
  PROCESSOAtivos INT NULL, 
  PROCESSOTotal INT NULL,
  dtHora DATETIME NULL
);

CREATE TABLE IF NOT EXISTS alertaM_N (
  idAlerta INT NOT NULL AUTO_INCREMENT,
  tipo VARCHAR(45) NULL,
  gravidade VARCHAR(45) NOT NULL,
  medida DOUBLE NULL,
  dtHora DATETIME NULL,
  fkCaptura INT NOT NULL,
  PRIMARY KEY (idAlerta),
  CONSTRAINT fk_alertaM_N_capturaM_N1
  FOREIGN KEY (fkCaptura) REFERENCES capturaM_N (idCaptura)
);
